apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: assignment
spec:
  rules:
    - host: person-service.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: person-service
                port:
                  number: 8080